### ISSUE TITLE
How to configure SET & CLR for SAMD21E15B?

### ISSUE THREAD

**Issue by RojasMilo** [cpldcpu/light_ws2812#35]
Hi I'm trying to use in an SAMD21E15B 

![captura](https://cloud.githubusercontent.com/assets/20142943/19314531/1855f01e-9060-11e6-8cb7-32468dc8d55e.PNG)

But I do not know how to write the address of the data port register to set the pin, I'm using the PA14 pin

![captura1](https://cloud.githubusercontent.com/assets/20142943/19314752/df9f4792-9060-11e6-9188-da48239e9f07.PNG)

Thank you.

**Comment by Soldia1138** [comment]
There are two errors in your line:
`PORT->Group[0]->OUTSET.bit[14]` isn't the correct syntax.

First of all the _OUTSET_ is part of the _Group_ *struct*, so it should be
`PORT->Group[0].OUTSET`

The next one is the bit address. You need to either address the bit (_bit_) itself or the whole register (_reg_). Technically it doesn't really matter, because it is a union the definition is:
```
typedef union {
  struct {
    uint32_t OUTSET:32;        /*!< bit:  0..31  Port Data Output Value Set         */
  } bit;                       /*!< Structure used for bit  access                  */
  uint32_t reg;                /*!< Type      used for register access              */
} PORT_OUTSET_Type;
```

So you can either type:
`PORT->Group[0].OUTSET.reg = PORT_PA14;`
or
`PORT->Group[0].OUTSET.bit.OUTSET = PORT_PA14;`

**Comment by cpldcpu** [comment]
Thanks to soldia for solving this. Closing.
