### ISSUE TITLE
Max led count is 24

### ISSUE THREAD

**Issue by Rainbrony** [cpldcpu/light_ws2812#70]
using attiny85, Arduino IDE, the max led count is 24, doesn't work if set above 24

**Comment by codesoap** [comment]
I've not yet used this library, but take a look at #66. The attiny85 only has 512 bytes of RAM and the Arduino bootloader probably uses up a good share of it.

**Comment by codesoap** [comment]
The attiny only has 512 bytes of ram. The array for 24LEDs will take up 72 bytes already. You didn't write what else you are doing in the program, but I'd guess the RAM is used up.

Maybe you could try using raw C, so that you can easier manage your RAM usage.

What is the error you get when using more than 24 LEDs?

**Comment by Rainbrony** [comment]
thanks mate
